@extends('layouts.production', ['title' => 'Nachkalkulation'])
@section('content')
<div class="seitenkopf"><div><h1>Nachkalkulation @if($order){{ $order->number }}@endif</h1><p class="leise">Soll-Ist-Vergleich auf Basis der erfassten Arbeitszeit</p></div><form method="GET" action="{{ route('costing') }}" class="knopfleiste"><label for="order">Auftrag</label><select id="order" name="order">@foreach($orders as $item)<option value="{{ $item->id }}" @selected($item->id === $order?->id)>{{ $item->number }} · {{ $item->article->name }}</option>@endforeach</select><button class="btn btn-sekundaer">Anzeigen</button></form></div>
@if($order)
@php $plannedCost = 0; $actualCost = 0; @endphp
<section class="karte"><h2>Soll-Ist-Vergleich je Arbeitsgang</h2><div class="tabelle-scroll"><table><thead><tr><th>AG</th><th>Arbeitsgang</th><th class="zahl">Soll-Zeit</th><th class="zahl">Ist-Zeit</th><th class="zahl">Abweichung</th><th class="zahl">Soll-Kosten</th><th class="zahl">Ist-Kosten</th></tr></thead><tbody>@foreach($order->operations as $op)@php $plan = $op->planned_minutes / 60 * $op->hourly_rate; $actual = $op->actual_minutes / 60 * $op->hourly_rate; $plannedCost += $plan; $actualCost += $actual; @endphp<tr><td>{{ $op->sequence }}</td><td>{{ $op->name }}</td><td class="zahl">{{ number_format($op->planned_minutes, 1, ',', '.') }}</td><td class="zahl">{{ number_format($op->actual_minutes, 1, ',', '.') }}</td><td class="zahl">{{ number_format($op->actual_minutes - $op->planned_minutes, 1, ',', '.') }}</td><td class="zahl">{{ number_format($plan, 2, ',', '.') }} €</td><td class="zahl">{{ number_format($actual, 2, ',', '.') }} €</td></tr>@endforeach</tbody><tfoot><tr><td colspan="5">Gesamt</td><td class="zahl">{{ number_format($plannedCost, 2, ',', '.') }} €</td><td class="zahl">{{ number_format($actualCost, 2, ',', '.') }} €</td></tr></tfoot></table></div></section>
<section class="karte"><h2>Ergebnis</h2><p>Abweichung: <strong>{{ number_format($actualCost - $plannedCost, 2, ',', '.') }} €</strong> · Ist-Kosten pro Stück: <strong>{{ number_format($actualCost / $order->quantity, 2, ',', '.') }} €</strong></p><p class="leise">Unterbrechungen sind in den Ist-Kosten nicht enthalten.</p></section>
@else<section class="karte">Noch kein Auftrag ist fertig gemeldet.</section>@endif
@endsection
