<div>
    <p class="klein"><a href="{{ route('orders.index') }}">← Zurück zu den Aufträgen</a></p>
    <div class="seitenkopf"><div><h1>Auftrag {{ $order->number }} <span class="badge {{ $order->status === 'in_arbeit' ? 'in-arbeit' : $order->status }}">{{ str_replace('_', ' ', $order->status) }}</span></h1><p class="leise">{{ $order->article->code }} {{ $order->article->name }}</p></div><div class="knopfleiste">@if($order->status === 'angelegt')<button wire:click="setStatus('freigegeben')" class="btn btn-primaer">Freigeben</button><button wire:click="setStatus('storniert')" wire:confirm="Auftrag wirklich stornieren?" class="btn btn-sekundaer">Stornieren</button>@endif</div></div>
    <section class="karte"><h2>Kopfdaten</h2><dl class="kopfdaten"><dt>Menge</dt><dd>{{ $order->quantity }} Stück</dd><dt>Liefertermin</dt><dd>{{ $order->due_date->format('d.m.Y') }}</dd><dt>Kunde</dt><dd>{{ $order->customer ?: '–' }}</dd><dt>Bemerkung</dt><dd>{{ $order->notes ?: '–' }}</dd></dl></section>
    <section class="karte"><h2>Arbeitsgänge</h2><div class="tabelle-scroll"><table><thead><tr><th>AG</th><th>Arbeitsgang</th><th>Arbeitsplatz</th><th>Status</th><th class="zahl">Soll</th><th class="zahl">Ist</th><th class="zahl">Soll-Kosten</th><th class="zahl">Ist-Kosten</th></tr></thead><tbody>
        @foreach($order->operations as $operation)<tr><td>{{ $operation->sequence }}</td><td>{{ $operation->name }}</td><td>{{ $operation->workstation->name }}</td><td>{{ str_replace('_', ' ', $operation->status) }}</td><td class="zahl">{{ number_format($operation->planned_minutes, 1, ',', '.') }} min</td><td class="zahl">{{ number_format($operation->actual_minutes, 1, ',', '.') }} min</td><td class="zahl">{{ number_format($operation->planned_minutes / 60 * $operation->hourly_rate, 2, ',', '.') }} €</td><td class="zahl">{{ number_format($operation->actual_minutes / 60 * $operation->hourly_rate, 2, ',', '.') }} €</td></tr>@endforeach
    </tbody></table></div></section>
    <section class="karte"><h2>Zeitbuchungen</h2><div class="tabelle-scroll"><table><thead><tr><th>AG</th><th>Person</th><th>Art</th><th>Von</th><th>Bis</th><th class="zahl">Minuten</th><th>Bemerkung</th></tr></thead><tbody>
        @forelse($order->operations->flatMap->entries->sortByDesc('started_at') as $entry)<tr><td>{{ $entry->operation->sequence }}</td><td>{{ $entry->user->name }}</td><td>{{ ['setup' => 'Rüsten', 'run' => 'Bearbeiten', 'interruption' => 'Unterbrechung'][$entry->kind] ?? $entry->kind }} {{ $entry->reason }}</td><td>{{ $entry->started_at->format('d.m.Y H:i') }}</td><td>{{ $entry->ended_at?->format('d.m.Y H:i') ?? 'läuft' }}</td><td class="zahl">{{ $entry->ended_at ? number_format($entry->minutes, 1, ',', '.') : '–' }}</td><td>{{ $entry->notes }}</td></tr>@empty<tr><td colspan="7">Noch keine Buchungen.</td></tr>@endforelse
    </tbody></table></div></section>
    @if(auth()->user()->role === 'admin')<form wire:submit="addEntry" class="karte"><h2>Buchung nachtragen</h2><div class="formular-raster"><div class="feld"><label>Arbeitsgang</label><select wire:model="operationId"><option value="">Bitte wählen</option>@foreach($order->operations as $operation)<option value="{{ $operation->id }}">{{ $operation->sequence }} {{ $operation->name }}</option>@endforeach</select>@error('operationId')<small>{{ $message }}</small>@enderror</div><div class="feld"><label>Art</label><select wire:model="kind"><option value="setup">Rüsten</option><option value="run">Bearbeiten</option></select></div><div class="feld"><label>Von</label><input type="datetime-local" wire:model="startedAt">@error('startedAt')<small>{{ $message }}</small>@enderror</div><div class="feld"><label>Bis</label><input type="datetime-local" wire:model="endedAt">@error('endedAt')<small>{{ $message }}</small>@enderror</div></div><div class="feld"><label>Bemerkung</label><input wire:model="notes"></div><button class="btn btn-primaer" type="submit">Buchung speichern</button></form>@endif
</div>
